Fix billing.go aws.GetStartTimeEndTime (#21531)
This PR is to fix this error introduced in https://github.com/elastic/beats/pull/20875:
```
# github.com/elastic/beats/v7/x-pack/metricbeat/module/aws/billing
../x-pack/metricbeat/module/aws/billing/billing.go:119:47: not enough arguments in call to "github.com/elastic/beats/v7/x-pack/metricbeat/module/aws".GetStartTimeEndTime
	have (time.Duration)
	want (time.Duration, time.Duration)
Error: error getting default metricsets: Error running subcommand to get metricsets: running "go run /home/travis/gopath/src/github.com/elastic/beats/x-pack/metricbeat/scripts/msetlists/main.go" failed with exit code 2
```