Revert "add a DEB integration test (#4301)" (#4419)
This reverts commit 4fd31f1bbb1671cd7cfb23bc7f6f8746197e27a4.

The Serverless Beats Tests step in our daily builds started failing with:

> Error: error running test: missing required Elastic Agent package builds for integration runner to execute: /tmp/beats-build/beats/x-pack/metricbeat/build/distributions/elastic-agent-8.14.0-SNAPSHOT-linux-x86_64.tar.gz, /tmp/beats-build/beats/x-pack/metricbeat/build/distributions/elastic-agent-8.14.0-SNAPSHOT-linux-x86_64.tar.gz.sha512, /tmp/beats-build/beats/x-pack/metricbeat/build/distributions/elastic-agent-8.14.0-SNAPSHOT-x86_64.rpm, /tmp/beats-build/beats/x-pack/metricbeat/build/distributions/elastic-agent-8.14.0-SNAPSHOT-x86_64.rpm.sha512, /tmp/beats-build/beats/x-pack/metricbeat/build/distributions/elastic-agent-8.14.0-SNAPSHOT-amd64.deb, /tmp/beats-build/beats/x-pack/metricbeat/build/distributions/elastic-agent-8.14.0-SNAPSHOT-amd64.deb.sha512
~/builds/bk-agent-prod-gcp-1710406561496364062/elastic/elastic-agent

The last successful build is https://buildkite.com/elastic/elastic-agent/builds/7707
The first failure is https://buildkite.com/elastic/elastic-agent/builds/7735

There were only 2 changes made between these, this change is one of them. Let's try to revert this first because it has the least impact.